### ISSUE TITLE
Multiclass Prediction

### ISSUE THREAD

**Issue by XuZikang** [ys-zong/MEDFAIR#1]
Hello, really impressive work. and how can I use this framework for multiclass classification tasks? For example, using the original label of HAM10000 (7 classes) as target task, rather than spliting the dataset into benign and maglinant?

Thank you!

**Comment by ys-zong** [comment]
Hi, thanks for your interest. We may try to support this feature in the future. For now, there're a few things to modify:

- Change the loss function from BCE to CE.
- Set the output layer to 7 instead of 1.
- AUC may not be suitable for non-binary tasks. You may want to change it to Acc.

Let me know if you have any other questions~

**Comment by XuZikang** [comment]
Thank you for your reply!

I'm trying to train models follow your default settings, and there seems some bugs in CFair and LAFTR. Besides, I've figured out some small bugs in DSBN and EnD :)
